name: 02 - Workflow Events

on:
  pull_request:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-18.04
    steps:
      - name: Show the trigger
        run: |
          echo "Even name: ${{ github.event_name }}"